In [5]:
import pandas as pd

sensors = pd.read_csv('./air-quality-data-from-extensive-network-of-sensors/sensor_locations.csv')

In [3]:
def get_query(t, x):
    return """
    IMPORT {} from {}
    """.format(t,x)

In [4]:
get_query('a', 'b')

'\n    IMPORT a from b\n    '

In [7]:
sensors.shape[0]

56

In [12]:
sensors['dummy'] = [i for i in range(sensors.shape[0])]

In [14]:
sensors

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>latitude</th>
      <th>longitude</th>
      <th>dummy</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3</td>
      <td>50.057748</td>
      <td>19.961375</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>140</td>
      <td>50.057747</td>
      <td>19.961374</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>142</td>
      <td>50.084816</td>
      <td>19.878066</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>147</td>
      <td>50.048924</td>
      <td>19.962262</td>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>169</td>
      <td>50.048699</td>
      <td>20.101569</td>
      <td>4</td>
    </tr>
    <tr>
      <th>5</th>
      <td>170</td>
      <td>50.077467</td>
      <td>19.895577</td>
      <td>5</td>
    </tr>
    <tr>
      <th>6</th>
      <td>171</td>
      <td>50.084134</td>
      <td>19.968416</td>
      <td>6</td>
    </tr>
    <tr>
      <th>7</th>
      <td>172</td>
      <td>50.073094</td>
      <td>19.886750</td>
      <td>7</td>
    </tr>
    <tr>
      <th>8</th>
      <td>173</td>
      <td>50.057537</td>
      <td>19.897547</td>
      <td>8</td>
    </tr>
    <tr>
      <th>9</th>
      <td>174</td>
      <td>50.057242</td>
      <td>19.914874</td>
      <td>9</td>
    </tr>
    <tr>
      <th>10</th>
      <td>176</td>
      <td>50.044067</td>
      <td>19.998804</td>
      <td>10</td>
    </tr>
    <tr>
      <th>11</th>
      <td>177</td>
      <td>50.093619</td>
      <td>19.924138</td>
      <td>11</td>
    </tr>
    <tr>
      <th>12</th>
      <td>178</td>
      <td>50.033195</td>
      <td>19.900714</td>
      <td>12</td>
    </tr>
    <tr>
      <th>13</th>
      <td>179</td>
      <td>50.077690</td>
      <td>19.935777</td>
      <td>13</td>
    </tr>
    <tr>
      <th>14</th>
      <td>180</td>
      <td>50.018006</td>
      <td>19.983935</td>
      <td>14</td>
    </tr>
    <tr>
      <th>15</th>
      <td>181</td>
      <td>50.055163</td>
      <td>19.947015</td>
      <td>15</td>
    </tr>
    <tr>
      <th>16</th>
      <td>182</td>
      <td>50.020586</td>
      <td>20.022960</td>
      <td>16</td>
    </tr>
    <tr>
      <th>17</th>
      <td>183</td>
      <td>50.098304</td>
      <td>19.879415</td>
      <td>17</td>
    </tr>
    <tr>
      <th>18</th>
      <td>184</td>
      <td>50.047736</td>
      <td>19.919646</td>
      <td>18</td>
    </tr>
    <tr>
      <th>19</th>
      <td>185</td>
      <td>50.085470</td>
      <td>19.899209</td>
      <td>19</td>
    </tr>
    <tr>
      <th>20</th>
      <td>187</td>
      <td>50.096969</td>
      <td>19.914774</td>
      <td>20</td>
    </tr>
    <tr>
      <th>21</th>
      <td>189</td>
      <td>50.062418</td>
      <td>19.928368</td>
      <td>21</td>
    </tr>
    <tr>
      <th>22</th>
      <td>192</td>
      <td>50.065128</td>
      <td>19.867504</td>
      <td>22</td>
    </tr>
    <tr>
      <th>23</th>
      <td>194</td>
      <td>50.073167</td>
      <td>20.027745</td>
      <td>23</td>
    </tr>
    <tr>
      <th>24</th>
      <td>195</td>
      <td>50.066686</td>
      <td>19.997208</td>
      <td>24</td>
    </tr>
    <tr>
      <th>25</th>
      <td>196</td>
      <td>50.066747</td>
      <td>19.962083</td>
      <td>25</td>
    </tr>
    <tr>
      <th>26</th>
      <td>201</td>
      <td>50.054907</td>
      <td>19.956501</td>
      <td>26</td>
    </tr>
    <tr>
      <th>27</th>
      <td>202</td>
      <td>50.005587</td>
      <td>19.928973</td>
      <td>27</td>
    </tr>
    <tr>
      <th>28</th>
      <td>203</td>
      <td>50.083454</td>
      <td>20.057153</td>
      <td>28</td>
    </tr>
    <tr>
      <th>29</th>
      <td>204</td>
      <td>50.062006</td>
      <td>19.940984</td>
      <td>29</td>
    </tr>
    <tr>
      <th>30</th>
      <td>205</td>
      <td>50.088719</td>
      <td>19.910314</td>
      <td>30</td>
    </tr>
    <tr>
      <th>31</th>
      <td>208</td>
      <td>50.099239</td>
      <td>19.953954</td>
      <td>31</td>
    </tr>
    <tr>
      <th>32</th>
      <td>209</td>
      <td>50.108024</td>
      <td>19.896124</td>
      <td>32</td>
    </tr>
    <tr>
      <th>33</th>
      <td>210</td>
      <td>50.062677</td>
      <td>20.018922</td>
      <td>33</td>
    </tr>
    <tr>
      <th>34</th>
      <td>211</td>
      <td>50.044424</td>
      <td>19.952205</td>
      <td>34</td>
    </tr>
    <tr>
      <th>35</th>
      <td>212</td>
      <td>50.055138</td>
      <td>19.894570</td>
      <td>35</td>
    </tr>
    <tr>
      <th>36</th>
      <td>213</td>
      <td>50.067503</td>
      <td>19.906294</td>
      <td>36</td>
    </tr>
    <tr>
      <th>37</th>
      <td>214</td>
      <td>50.071719</td>
      <td>19.962347</td>
      <td>37</td>
    </tr>
    <tr>
      <th>38</th>
      <td>215</td>
      <td>50.096693</td>
      <td>19.993572</td>
      <td>38</td>
    </tr>
    <tr>
      <th>39</th>
      <td>216</td>
      <td>50.043527</td>
      <td>19.925963</td>
      <td>39</td>
    </tr>
    <tr>
      <th>40</th>
      <td>218</td>
      <td>50.042476</td>
      <td>19.826993</td>
      <td>40</td>
    </tr>
    <tr>
      <th>41</th>
      <td>219</td>
      <td>50.107347</td>
      <td>20.045773</td>
      <td>41</td>
    </tr>
    <tr>
      <th>42</th>
      <td>220</td>
      <td>50.079672</td>
      <td>19.949190</td>
      <td>42</td>
    </tr>
    <tr>
      <th>43</th>
      <td>221</td>
      <td>50.085346</td>
      <td>20.007551</td>
      <td>43</td>
    </tr>
    <tr>
      <th>44</th>
      <td>222</td>
      <td>50.040717</td>
      <td>19.869575</td>
      <td>44</td>
    </tr>
    <tr>
      <th>45</th>
      <td>223</td>
      <td>50.025251</td>
      <td>19.937998</td>
      <td>45</td>
    </tr>
    <tr>
      <th>46</th>
      <td>225</td>
      <td>50.020756</td>
      <td>19.844076</td>
      <td>46</td>
    </tr>
    <tr>
      <th>47</th>
      <td>226</td>
      <td>49.998480</td>
      <td>19.902375</td>
      <td>47</td>
    </tr>
    <tr>
      <th>48</th>
      <td>227</td>
      <td>50.037680</td>
      <td>19.990546</td>
      <td>48</td>
    </tr>
    <tr>
      <th>49</th>
      <td>228</td>
      <td>50.013156</td>
      <td>19.906306</td>
      <td>49</td>
    </tr>
    <tr>
      <th>50</th>
      <td>263</td>
      <td>49.999615</td>
      <td>19.966073</td>
      <td>50</td>
    </tr>
    <tr>
      <th>51</th>
      <td>622</td>
      <td>50.044418</td>
      <td>19.952200</td>
      <td>51</td>
    </tr>
    <tr>
      <th>52</th>
      <td>713</td>
      <td>50.032902</td>
      <td>19.900930</td>
      <td>52</td>
    </tr>
    <tr>
      <th>53</th>
      <td>808</td>
      <td>50.096970</td>
      <td>19.914774</td>
      <td>53</td>
    </tr>
    <tr>
      <th>54</th>
      <td>857</td>
      <td>50.037663</td>
      <td>19.990601</td>
      <td>54</td>
    </tr>
    <tr>
      <th>55</th>
      <td>895</td>
      <td>50.084966</td>
      <td>19.877998</td>
      <td>55</td>
    </tr>
  </tbody>
</table>
</div>